import React,{useEffect,useState} from 'react';
import {ops} from '../../pages/OperationsPage';
import {LocationItem} from '../../types';
const box='rounded-xl border border-slate-700 bg-[#0c1527] p-4 sm:p-6 space-y-4';
const input='w-full rounded-lg border border-slate-600 bg-slate-900 p-3 text-white';
const button='rounded-lg bg-blue-600 px-4 py-3 disabled:opacity-50';
export function ConnectivityPanel({assets}:{assets:any[]}){
 const [roads,setRoads]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState<any>(null),[result,setResult]=useState<any>(null);
 async function refresh(){try{setRoads(await ops('/roads'));}catch(e:any){setError(e.message);}}
 useEffect(()=>{void refresh();},[]);
 const assetOptions=<><option value="">Select an asset</option>{assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</>;
 async function save(e:React.FormEvent<HTMLFormElement>){
  e.preventDefault();setBusy(true);setError('');const form=e.currentTarget;const data:any=Object.fromEntries(new FormData(form));
  try{data.observed_at=new Date(data.observed_at).toISOString();data.coordinates=data.coordinates.trim()?JSON.parse(data.coordinates):null;await ops(edit?`/roads/${edit.id}`:'/roads',{method:edit?'PUT':'POST',body:JSON.stringify(data)});setEdit(null);form.reset();setResult(null);await refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}
 }
 return <section className={box}><h2 className="text-xl font-semibold">Road connectivity and status</h2><p>Register surveyed links between vulnerability assets. View them using the Road connectivity layer in Map Explorer. Endpoint-only links are dashed schematic connections, not surveyed road shapes.</p><p className="text-sm text-slate-400">Status observations expire after 24 hours. Connectivity checks use fresh open links only; field confirmation is required before travel.</p>{error&&<p role="alert" className="text-rose-300">{error}</p>}
 <form key={edit?.id||'new'} onSubmit={save} className="space-y-3"><h3 className="font-semibold">{edit?'Update road status':'Register connection'}</h3><label className="block">Road name<input name="name" className={input} minLength={2} maxLength={120} defaultValue={edit?.name} required/></label><div className="grid sm:grid-cols-2 gap-3"><label>From asset<select aria-label="From asset" name="from_asset" className={input} defaultValue={edit?.from_asset} required>{assetOptions}</select></label><label>To asset<select aria-label="To asset" name="to_asset" className={input} defaultValue={edit?.to_asset} required>{assetOptions}</select></label><label>Road status<select aria-label="Road status" name="status" className={input} defaultValue={edit?.status||'unknown'}>{['open','restricted','blocked','unknown'].map(s=><option key={s}>{s}</option>)}</select></label><label>Observed at (local time)<input name="observed_at" className={input} type="datetime-local" required defaultValue={edit?.observed_at?new Date(new Date(edit.observed_at).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):undefined}/></label></div><label className="block">Survey / officer source<input className={input} name="source" minLength={3} maxLength={300} required defaultValue={edit?.source}/></label><details><summary>Optional surveyed road geometry</summary><label>WGS84 coordinate array: [[longitude, latitude], …]<textarea className={input} name="coordinates" rows={3} defaultValue={edit&&!edit.schematic?JSON.stringify(edit.coordinates):''}/></label></details><button disabled={busy||assets.length<2} className={button}>{busy?'Saving…':'Save road'}</button>{edit&&<button type="button" className="ml-3 underline" onClick={()=>setEdit(null)}>Cancel</button>}{assets.length<2&&<p>Register at least two vulnerability assets first.</p>}</form>
 <form className="space-y-3 border-t border-slate-700 pt-4" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const f=new FormData(e.currentTarget);setResult(await ops(`/roads/connectivity/check?${new URLSearchParams({from_asset:String(f.get('from')),to_asset:String(f.get('to'))})}`));}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><h3 className="font-semibold">Check connectivity</h3><div className="grid sm:grid-cols-2 gap-3"><label>Start<select aria-label="Start" name="from" className={input} required>{assetOptions}</select></label><label>Destination<select aria-label="Destination" name="to" className={input} required>{assetOptions}</select></label></div><button className={button} disabled={busy||assets.length<2}>Check open links</button>{result&&<div role="status"><strong>{result.connected?'Connected in recorded network':'No recorded open connection'}</strong><p>{result.basis}</p>{result.road_ids.length>0&&<p>{result.road_ids.map((id:string)=>roads.find(r=>r.id===id)?.name||id).join(' → ')}</p>}</div>}</form>
 <div className="space-y-3">{!roads.length&&<p>No roads registered.</p>}{roads.map(r=><article key={r.id} className="border-t border-slate-700 pt-3"><strong>{r.name} · {r.effective_status.toUpperCase()}</strong><p className="text-sm">{r.schematic?'Schematic link':'Surveyed geometry'} · {new Date(r.observed_at).toLocaleString()} · Source: {r.source}</p>{r.stale&&<p className="text-amber-300">Stale observation — reconfirm status.</p>}{r.missing_endpoint&&<p className="text-amber-300">An endpoint asset was removed. Update this connection.</p>}<button className="underline mr-4" onClick={()=>setEdit(r)}>Edit / reconfirm</button><button className="text-rose-300" onClick={async()=>{if(!confirm(`Delete ${r.name}?`))return;try{await ops(`/roads/${r.id}`,{method:'DELETE'});setResult(null);await refresh();}catch(e:any){setError(e.message);}}}>Delete</button></article>)}</div></section>;
}
export function SatellitePanel({locations}:{locations:LocationItem[]}){
 const [id,setId]=useState(''),[observation,setObservation]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let cancelled=false;setObservation(null);setError('');if(id){setBusy(true);ops(`/satellite/${encodeURIComponent(id)}`).then(d=>{if(!cancelled)setObservation(d.observation);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});}return()=>{cancelled=true};},[id]);
 return <section className={box}><h2 className="text-xl font-semibold">Satellite vegetation observations</h2><p>Fetch measured MODIS NDVI for a monitoring site. This is a 250 m, 16-day composite, not a live image or a landslide forecast. Cloudy, snow-covered, marginal and missing pixels are rejected.</p><label className="block">Monitoring site<select className={input} value={id} disabled={busy} onChange={e=>setId(e.target.value)}><option value="">Select a location</option>{locations.map(l=><option key={l.location_id} value={l.location_id}>{l.name}</option>)}</select></label><button className={button} disabled={!id||busy} onClick={async()=>{setBusy(true);setError('');try{const data=await ops(`/satellite/${encodeURIComponent(id)}/refresh`,{method:'POST',signal:AbortSignal.timeout(35000)});setObservation(data.observation);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{busy?'Fetching satellite observation…':'Fetch latest quality-approved NDVI'}</button>{error&&<p role="alert" className="text-rose-300">{error}</p>}{observation?<div className="rounded-lg border border-slate-600 p-4 space-y-2"><strong className="text-2xl">NDVI {observation.ndvi.toFixed(4)}</strong><p>Composite: {observation.composite_date} · {observation.age_days} days old {observation.stale&&'· STALE'}</p><p>{observation.source} · {observation.product} · {observation.quality}</p><p className="text-sm">Fetched {new Date(observation.retrieved_at).toLocaleString()}. Requests use a one-hour cache.</p><p>Use the satellite NDVI button in Prediction Simulator to load this observation into a simulation. Operational predictions remain unchanged.</p></div>:<p>No saved satellite observation for this site.</p>}</section>;
}
