import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {mkdtempSync,writeFileSync} from 'node:fs';
import {join,dirname,delimiter} from 'node:path';
import {fileURLToPath} from 'node:url';
import {tmpdir} from 'node:os';
import {createRequire} from 'node:module';
const verificationDir=dirname(fileURLToPath(import.meta.url));
const root=dirname(verificationDir);
const testDirectory=mkdtempSync(join(tmpdir(),'ner-browser-'));
const testDatabase='sqlite:///'+join(testDirectory,'test.db').split(String.fromCharCode(92)).join('/');
import assert from 'node:assert/strict';
const require=createRequire(join(root,'frontend/package.json'));
const {chromium:pw}=await import(process.env.PLAYWRIGHT_MODULE || require.resolve('playwright'));
const base='http://127.0.0.1:8134';
const spawnServer=()=>spawn(process.env.PYTHON || 'python',['-m','uvicorn','app.main:app','--host','127.0.0.1','--port','8134'],{cwd:join(root,'backend'),env:{...process.env,PYTHONPATH:[join(root,'backend'),process.env.PYTHONPATH].filter(Boolean).join(delimiter),WEATHER_PROVIDER:'simulated',WHATSAPP_ENABLED:'false',DATABASE_URL:testDatabase},stdio:['ignore','pipe','pipe']});
let server=spawnServer();
let logs='';server.stdout.on('data',x=>logs+=x);server.stderr.on('data',x=>logs+=x);process.on('exit',()=>server.kill());
let browser;
try{
 for(let i=0;i<100;i++){try{if((await fetch(base+'/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,150));}
 browser=await pw.launch({executablePath:process.env.BROWSER_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.addInitScript(()=>{if(!localStorage.getItem('migration-fixture')){localStorage.setItem('migration-fixture','true');localStorage.setItem('ner-field-outbox-v1',JSON.stringify([{id:'legacy-browser-report',location_id:'LOC-AS-01',officer:'Legacy queue test',category:'other',severity:'LOW',latitude:26.1,longitude:91.7,notes:'Legacy queued observation',observed_at:new Date().toISOString()}]));}});
 const page=await context.newPage();const errors=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>{errors.push(e.message);console.log('PAGEERROR',e.message);});
 await page.goto(base,{waitUntil:'domcontentloaded'});
 await page.getByRole('button',{name:'Field Operations',exact:true}).filter({visible:true}).click();
 await page.evaluate(()=>navigator.serviceWorker.ready.then(()=>true));
 await page.waitForFunction(async()=>!(await window.NEROutbox.all()).length&&!localStorage.getItem('ner-field-outbox-v1'));
 const migrated=await (await fetch(base+'/api/operations/reports')).json();assert.equal(migrated.filter(r=>r.id==='legacy-browser-report').length,1);
 await page.reload({waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
 await page.getByRole('button',{name:'Field Operations',exact:true}).filter({visible:true}).click();
 await page.getByRole('button',{name:'Road connectivity',exact:true}).click();
 await page.getByRole('heading',{name:'Road connectivity and status'}).waitFor();
 const assetIds=[];
 for(const [name,lon] of [['Connectivity start',91.7],['Connectivity shelter',91.8]]){
  const r=await fetch(base+'/api/operations/assets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,location_id:'LOC-AS-01',kind:'shelter',latitude:26.1,longitude:lon,population:100,vulnerability:.5,access:'open',source:'Browser verification fixture'})});assert(r.ok);assetIds.push((await r.json()).id);
 }
 await page.getByRole('button',{name:'Response queue',exact:true}).click();await page.getByRole('button',{name:'Refresh queue',exact:true}).click();
 await page.getByText('Connectivity start',{exact:true}).waitFor();await page.getByRole('button',{name:'Road connectivity',exact:true}).click();
 await page.getByLabel('Road name',{exact:true}).fill('Browser surveyed connection');await page.getByLabel('From asset',{exact:true}).selectOption(assetIds[0]);await page.getByLabel('To asset',{exact:true}).selectOption(assetIds[1]);await page.getByLabel('Road status',{exact:true}).selectOption('open');
 await page.getByLabel('Observed at (local time)',{exact:true}).fill(new Date().toISOString().slice(0,16));await page.getByLabel('Survey / officer source',{exact:true}).fill('Browser verified observation');await page.getByRole('button',{name:'Save road',exact:true}).click();
 await page.getByText('Browser surveyed connection · OPEN',{exact:true}).waitFor();
 await page.getByLabel('Start',{exact:true}).selectOption(assetIds[0]);await page.getByLabel('Destination',{exact:true}).selectOption(assetIds[1]);await page.getByRole('button',{name:'Check open links',exact:true}).click();await page.getByText('Connected in recorded network',{exact:true}).waitFor();
 await page.getByRole('button',{name:'GIS Explorer',exact:true}).filter({visible:true}).click();await page.getByRole('checkbox',{name:'Road connectivity'}).check();
 await page.waitForFunction(()=>!!document.querySelector('path[stroke="#34d399"]'));
 await page.locator('main h4').first().click();
 const stacking=await page.evaluate(()=>{const drawer=document.querySelector('.fixed.inset-y-0.right-0');const r=drawer.getBoundingClientRect();return drawer.contains(document.elementFromPoint(r.left+30,Math.min(r.bottom-20,400)));});assert(stacking,'Map must stay below location drawer');
 await page.screenshot({path:join(verificationDir,'map-drawer.png')});
 await page.locator('.fixed.inset-y-0.right-0 button').first().click();
 await page.getByRole('button',{name:'Early Warnings',exact:true}).filter({visible:true}).click();await page.getByLabel('Alert language',{exact:true}).selectOption('hi');await page.getByText('भूस्खलन चेतावनी · गंभीर',{exact:true}).first().waitFor();
 await page.getByLabel('Alert language',{exact:true}).selectOption('as');await page.locator('[lang="as"]').first().waitFor();await page.getByLabel('Alert language',{exact:true}).selectOption('bn');await page.locator('[lang="bn"]').first().waitFor();await page.getByLabel('Alert language',{exact:true}).selectOption('en');
 await page.getByRole('button',{name:'Field Operations',exact:true}).filter({visible:true}).click();
 await page.getByRole('button',{name:'Satellite NDVI',exact:true}).click();
 await page.getByLabel('Monitoring site').selectOption('LOC-AS-01');
 await page.getByText('No saved satellite observation for this site.').waitFor();
 await page.getByRole('button',{name:'Field report',exact:true}).click();
 await page.getByLabel('Officer name').fill('Offline video test');
 await page.getByLabel('Monitoring location',{exact:true}).selectOption('LOC-AS-01');
 await page.getByLabel('Latitude',{exact:true}).fill('26.1');await page.getByLabel('Longitude',{exact:true}).fill('91.7');
 await page.getByLabel('Observation details').fill('Offline video evidence verification');
 await page.getByLabel('Video (optional, MP4/WebM under 10 MB)').setInputFiles(join(verificationDir,'test-video.webm'));
 await page.getByRole('button',{name:'Save and submit report'}).waitFor();
 server.kill();await once(server,'exit');
 await page.getByRole('button',{name:'Save and submit report'}).click();
 await page.getByText(/^(Offline|Online) · 1 pending reports$/).waitFor();
 await page.getByRole('button',{name:'Save and submit report',exact:true}).waitFor();
 await page.goto(base+'/?offline-reopen=1',{waitUntil:'domcontentloaded'});
 await page.getByRole('button',{name:'Field Operations',exact:true}).filter({visible:true}).click();
 await page.getByText(/^(Offline|Online) · 1 pending reports$/).waitFor();
 const queue=await page.evaluate(()=>window.NEROutbox.all());assert(queue.length===1&&queue[0].report.video.startsWith('data:video/webm'));
 server=spawnServer();server.stdout.on('data',x=>logs+=x);server.stderr.on('data',x=>logs+=x);
 for(let i=0;i<100;i++){try{if((await fetch(base+'/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,150));}
 await page.evaluate(()=>window.dispatchEvent(new Event('online')));
 await page.getByText('Online · 0 pending reports',{exact:true}).waitFor({timeout:40000});
 await page.getByRole('button',{name:'Response queue',exact:true}).click();
 await page.getByRole('button',{name:'Refresh queue',exact:true}).click();
 await page.getByText('Offline video evidence verification',{exact:true}).waitFor();
 await page.getByRole('button',{name:'View evidence video'}).first().click();
 await page.getByRole('dialog').waitFor();
 const media=await page.locator('[role=dialog] video').evaluate(v=>new Promise(resolve=>{if(v.readyState>=1)resolve({duration:v.duration,error:v.error?.message});else{v.onloadedmetadata=()=>resolve({duration:v.duration,error:v.error?.message});v.onerror=()=>resolve({error:v.error?.message});}}));assert(media.duration>0&&!media.error,JSON.stringify(media));
 await page.getByRole('button',{name:'Close video'}).click();
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Field report',exact:true}).click();
 const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));assert(width.scroll<=width.viewport);
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:join(verificationDir,'mobile-field-report.png'),fullPage:true});
 assert.deepEqual(errors,[]);const result={legacyQueueMigrated:true,reconnectEventSync:true,roadCreated:true,roadConnectivity:true,roadMapLayer:true,drawerAboveMap:stacking,alertLanguages:4,serviceWorker:true,offlineReload:true,videoPersisted:true,reconnectedSync:true,videoPlaybackMetadata:media,mobileWidth:width,pageErrors:errors};writeFileSync(join(verificationDir,'browser-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(error){console.error(error);console.error(logs.slice(-1800));process.exitCode=1;}finally{if(browser)await browser.close();server.kill();}
