import React,{useEffect,useState} from 'react';
import {LocationItem} from '../types';
const BASE=(import.meta as any).env?.VITE_API_URL||'/api';
const input='w-full rounded-lg border border-slate-600 bg-slate-900 p-2 text-white';
const button='rounded-lg bg-blue-600 px-4 py-2 disabled:opacity-50';
const panel='rounded-xl border border-slate-700 bg-[#0c1527] p-4 space-y-4';
async function req(path:string,options:RequestInit={}){
 const r=await fetch(BASE+path,{...options,credentials:'include',headers:{'Content-Type':'application/json',...(sessionStorage.getItem('operations-token')?{'X-Operations-Key':sessionStorage.getItem('operations-token')!}:{}),...options.headers},signal:AbortSignal.timeout(45000)});
 const d=await r.json();if(!r.ok)throw new Error(typeof d.detail==='string'?d.detail:Array.isArray(d.detail)?d.detail.map((x:any)=>x.msg).join('; '):'Request failed');return d;
}
function download(name:string,value:any){const a=document.createElement('a');const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function When({value}:{value:any}){return <>{value?new Date(value).toLocaleString():'Unavailable'}</>}
export function ReadinessPage({locations}:{locations:LocationItem[]}){
 const [tab,setTab]=useState('outlook'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <div className="space-y-5 text-slate-100"><h1 className="text-2xl font-semibold">Monitoring and validation</h1><p className="text-slate-300">Experimental outlooks, observed conditions and evidence review. Outlooks do not generate crisis alerts.</p><div className="flex flex-wrap gap-2">{[['outlook','Weather outlook'],['evaluation','Historical replay'],['sensors','Sensors'],['review','Report review'],['messaging','Notification channels'],['models','Model versions']].map(([id,label])=><button key={id} disabled={busy} onClick={()=>{setTab(id);setError('');setNotice('')}} className={'rounded-lg px-3 py-2 '+(tab===id?'bg-blue-600':'bg-slate-800')}>{label}</button>)}</div><p className="text-sm text-slate-400">Administrative actions require sign-in under Settings → WhatsApp crisis alerts.</p>{error&&<p role="alert" className="rounded border border-rose-600 p-3 text-rose-200">{error}</p>}{notice&&<p role="status" className="rounded border border-emerald-700 p-3">{notice}</p>}{busy&&<p role="status">Working…</p>}
 {tab==='outlook'&&<OutlookPanel locations={locations} run={run} busy={busy}/>}
 {tab==='evaluation'&&<EvaluationPanel run={run} busy={busy}/>}
 {tab==='sensors'&&<SensorPanel locations={locations} run={run} busy={busy} notify={setNotice}/>}
 {tab==='review'&&<ReviewPanel run={run} busy={busy}/>}
 {tab==='messaging'&&<MessagingPanel run={run} busy={busy} notify={setNotice}/>}
 {tab==='models'&&<ModelPanel run={run} busy={busy}/>}
 </div>
}
type Props={run:(fn:()=>Promise<void>)=>Promise<void>;busy:boolean};
function OutlookPanel({locations,run,busy}:Props&{locations:LocationItem[]}){
 const [id,setId]=useState(locations[0]?.location_id||''),[data,setData]=useState<any>(null);
 useEffect(()=>{let cancelled=false;setData(null);if(id)void run(async()=>{const d=await req(`/readiness/outlooks/${encodeURIComponent(id)}`);if(!cancelled)setData(d)});return()=>{cancelled=true}},[id]);
 const latest=data?.history?.[0];
 return <section className={panel}><label>Monitoring location<select className={input} value={id} disabled={busy} onChange={e=>setId(e.target.value)}>{locations.map(l=><option key={l.location_id} value={l.location_id}>{l.name}</option>)}</select></label><button className={button} disabled={busy||!id} onClick={()=>run(async()=>{await req(`/readiness/outlooks/${encodeURIComponent(id)}/refresh`,{method:'POST'});setData(await req(`/readiness/outlooks/${encodeURIComponent(id)}`))})}>Fetch forecast</button>
 {data&&<div className="text-sm space-y-1"><p>Current location source: <strong>{data.current_input.source}</strong> · {data.current_input.stale?'Stale or timestamp unavailable':'Recent timestamp'}</p><p>Location timestamp: <When value={data.current_input.timestamp}/></p><p>Scheduled collection: {data.monitoring_enabled&&data.site_scheduled?'Enabled':'Not enabled for this location'}</p></div>}
 {!latest?<p>No forecast snapshot yet. Fetch a forecast to begin.</p>:<><div className="rounded bg-amber-950/50 p-3 text-amber-100"><strong>Experimental rainfall outlook — not a landslide probability</strong><p>{latest.method}</p><p>{latest.stale?'Snapshot is stale. Refresh before interpreting.':'Forecast snapshot available.'}</p></div><p>Retrieved <When value={latest.retrieved_at}/> · Provider issue time unavailable</p><p>Recent 24-hour rainfall: {latest.recent_24h_mm} mm · Modelled shallow-soil moisture: {latest.shallow_soil_moisture_percent}%</p>
 <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Window</th><th>Forecast rainfall</th><th>Rolling 24h total</th><th>Demo reference</th></tr></thead><tbody>{latest.windows.map((w:any)=><tr key={w.hours} className="border-t border-slate-700"><td className="py-3">Next {w.hours} hours</td><td>{w.forecast_rain_mm} mm</td><td>{w.rolling_24h_mm} mm</td><td>{w.screen==='ABOVE_DEMO_REFERENCE'?'Above 100 mm':'Below 100 mm'}</td></tr>)}</tbody></table></div><ul className="list-disc pl-5 text-sm text-slate-400">{latest.limitations.map((l:string)=><li key={l}>{l}</li>)}</ul>
 <h3 className="font-semibold">Snapshot history</h3><div className="max-h-72 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Retrieved</th><th>Recent 24h</th><th>Next 6h forecast</th></tr></thead><tbody>{data.history.map((h:any)=><tr key={h.retrieved_at}><td><When value={h.retrieved_at}/></td><td>{h.recent_24h_mm} mm</td><td>{h.windows.find((w:any)=>w.hours===6)?.forecast_rain_mm} mm</td></tr>)}</tbody></table></div></>}
 </section>
}
const template={threshold:.75,baseline_mm:100,rows:[{case_id:'replace-with-unique-case-id',location_id:'replace-with-location',source:'replace-with-verified-data-source',model_version:'replace-with-model-sha256',verified:false,issued_at:'2025-06-01T00:00:00Z',inputs_available_at:'2025-06-01T00:00:00Z',window_end:'2025-06-01T06:00:00Z',outcome_observed_until:'2025-06-01T06:00:00Z',event_at:null,probability:0.2,rainfall_24h_mm:20}]};
function EvaluationPanel({run,busy}:Props){
 const [payload,setPayload]=useState<any>(null),[result,setResult]=useState<any>(null),[saved,setSaved]=useState<any[]>([]),[step,setStep]=useState(0);
 return <section className={panel}><h2 className="text-xl font-semibold">Replay archived predictions against verified outcomes</h2><p>Import predictions that were issued before each outcome. The evaluator rejects future input availability, incomplete follow-up, mixed forecast horizons and duplicate case IDs. It does not regenerate historical forecasts or verify the uploader’s evidence.</p><button className={button} onClick={()=>download('replay-template.json',template)}>Download input template</button><label className="block">Evaluation JSON<input className={input} type="file" accept=".json,application/json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{setPayload(null);if(file.size>2000000)throw new Error('Maximum file size is 2 MB');const value=JSON.parse(await file.text());setPayload(value)})}}/></label><p>{payload?`${payload.rows?.length||0} records selected`:'Select a completed template. Example values are placeholders, not evaluation evidence.'}</p><div className="flex gap-2"><button className={button} disabled={busy||!payload} onClick={()=>run(async()=>{setResult(await req('/readiness/evaluations',{method:'POST',body:JSON.stringify(payload)}));setStep(0)})}>Evaluate and save</button><button className={button} disabled={busy} onClick={()=>run(async()=>setSaved(await req('/readiness/evaluations')))}>Load previous evaluations</button></div>{saved.map(s=><button key={s.id} className="block text-blue-300" onClick={()=>run(async()=>{setResult(await req(`/readiness/evaluations/${s.id}`));setStep(0)})}>{s.id.slice(0,8)} · {s.cases} cases · {s.horizon_hours}h window</button>)}
 {result&&<><p className="text-amber-200">{result.notice}</p><p>Evaluation ID: <code className="break-all">{result.id}</code></p><table className="w-full text-left"><thead><tr><th>Metric</th><th>Imported model</th><th>Rainfall baseline</th></tr></thead><tbody>{['tp','fp','fn','tn','precision','recall','false_alarm_ratio','false_positive_rate'].map(k=><tr key={k}><td>{k.replace(/_/g,' ')}</td><td>{result.model[k]==null?'Not defined':Number(result.model[k]).toFixed(3)}</td><td>{result.baseline[k]==null?'Not defined':Number(result.baseline[k]).toFixed(3)}</td></tr>)}</tbody></table><p>Brier score: {result.brier_score.toFixed(4)} · Mean detected lead time: {result.mean_detected_lead_hours==null?'Not defined':result.mean_detected_lead_hours.toFixed(2)+' hours'}</p><label className="block">Replay case {step+1} of {result.timeline.length}<input className="w-full" type="range" min={0} max={result.timeline.length-1} value={step} onChange={e=>setStep(Number(e.target.value))}/></label><div className="rounded bg-slate-900 p-3"><p>{result.timeline[step]?.case_id} · {result.timeline[step]?.location_id}</p><p>Issued: <When value={result.timeline[step]?.issued_at}/></p><p>Window ends: <When value={result.timeline[step]?.window_end}/></p><p>Prediction: {result.timeline[step]?.predicted?'Warning':'No warning'} · Observed outcome: {result.timeline[step]?.actual?'Event':'No event'}</p><p>Event time: <When value={result.timeline[step]?.event_at}/></p></div><button className={button} onClick={()=>download('evaluation-results.json',result)}>Download results</button></>}
 </section>
}
function SensorPanel({locations,run,busy,notify}:Props&{locations:LocationItem[];notify:(s:string)=>void}){
 const [devices,setDevices]=useState<any[]>([]),[token,setToken]=useState<any>(null),[readings,setReadings]=useState<any[]>([]);
 const load=async()=>setDevices(await req('/readiness/devices'));
 return <section className={panel}><h2 className="text-xl font-semibold">Sensor observations</h2><p>Register devices and collect timestamped readings. These observations are not automatically fed into the current prediction model or crisis messaging. Test devices remain labelled.</p><button className={button} disabled={busy} onClick={()=>run(load)}>Refresh devices</button><form className="grid sm:grid-cols-2 gap-3" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const d=Object.fromEntries(new FormData(form));void run(async()=>{setToken(await req('/readiness/devices',{method:'POST',body:JSON.stringify({...d,expected_interval_seconds:Number(d.expected_interval_seconds),test_device:d.test_device==='on'})}));await load()})}}><label>Name<input className={input} name="name" required minLength={2}/></label><label>Location<select className={input} name="location_id">{locations.map(l=><option key={l.location_id} value={l.location_id}>{l.name}</option>)}</select></label><label>Measurement<select name="kind" className={input}><option value="soil_moisture">Soil moisture (%)</option><option value="rainfall">Rainfall (mm)</option><option value="tilt">Tilt (degrees)</option><option value="pore_pressure">Pore pressure (kPa)</option></select></label><label>Expected interval (seconds)<input className={input} name="expected_interval_seconds" type="number" min={30} max={86400} defaultValue={900}/></label><label>Calibration record<input className={input} name="calibration_reference" required minLength={5}/></label><label className="flex gap-2 items-center"><input type="checkbox" name="test_device" defaultChecked/>Test device</label><button disabled={busy} className={button}>Register device</button></form>
 {token&&<div className="p-3 bg-amber-950/50 space-y-2"><p>Device ID: <code>{token.id}</code></p><p>Token is shown once. Copy it into the device configuration.</p><input className={input} readOnly type="password" value={token.token}/><button className={button} onClick={()=>run(async()=>{await navigator.clipboard.writeText(token.token);notify('Device token copied')})}>Copy token</button><button className="ml-3" onClick={()=>setToken(null)}>Dismiss</button><p className="text-sm">POST /api/readiness/sensor-ingest using the X-Sensor-Key header. See the included setup guide for the request format.</p></div>}
 {devices.map(d=><div key={d.id} className="border-t border-slate-700 py-3"><strong>{d.name}</strong> · {d.kind} · {d.test_device?'TEST':'Device observation'} · {d.active?(d.stale?'Stale/no reading':'Recent'):'Revoked'}<p className="text-sm">{d.id}</p>{d.latest&&<p>{d.latest.value} {d.latest.unit} · <When value={d.latest.observed_at}/></p>}<div className="flex gap-3"><button className="text-blue-300" disabled={busy} onClick={()=>run(async()=>setReadings(await req(`/readiness/devices/${d.id}/readings`)))}>Reading history</button><button className="text-rose-300" disabled={busy||!d.active} onClick={()=>{if(confirm('Revoke this device token?'))void run(async()=>{await req(`/readiness/devices/${d.id}/revoke`,{method:'POST'});await load()})}}>Revoke</button></div></div>)}<div className="max-h-64 overflow-auto">{readings.map(r=><p key={r.sequence_id}><When value={r.observed_at}/> · {r.value} {r.unit} · {r.source}</p>)}</div></section>
}
function ReviewPanel({run,busy}:Props){
 const [reports,setReports]=useState<any[]>([]),[report,setReport]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[boxes,setBoxes]=useState<any[]>([]),[start,setStart]=useState<any>(null);
 const select=async(id:string)=>{const r=await req('/operations/reports/'+id);setReport(r);setBoxes(r.annotations||[]);setStart(null);setHistory(await req('/readiness/audit/'+id))};
 return <section className={panel}><h2 className="text-xl font-semibold">Evidence and image review</h2><p>Human review only. Mark regions of interest on the photo and record your decision. No automatic crack detector or landslide prediction is applied to these images.</p><button className={button} disabled={busy} onClick={()=>run(async()=>setReports(await req('/operations/reports')))}>Load reports</button><select className={input} value={report?.id||''} disabled={busy} onChange={e=>{if(e.target.value)void run(()=>select(e.target.value))}}><option value="">Select a report</option>{reports.map(r=><option key={r.id} value={r.id}>{r.location_id} · {r.category} · {r.status} · {r.id.slice(0,8)}</option>)}</select>
 {report&&<><p>{report.notes}</p><p>Submitted by {report.officer} · Status {report.status}</p>{report.photo&&<><p className="text-sm">Click two opposite corners to mark a region. Coordinates are relative to the image, not a physical measurement.</p><div className="relative inline-block max-w-full cursor-crosshair" onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();const p={x:(e.clientX-rect.left)/rect.width,y:(e.clientY-rect.top)/rect.height};if(!start)setStart(p);else{const label=prompt('What do you observe?');if(label&&boxes.length<20){const b={x:Math.min(start.x,p.x),y:Math.min(start.y,p.y),width:Math.abs(p.x-start.x),height:Math.abs(p.y-start.y),label:label.slice(0,120)};if(b.width>.005&&b.height>.005)setBoxes([...boxes,b])}setStart(null)}}}><img src={report.photo} alt="Submitted field evidence" className="block max-h-[500px] max-w-full"/>{boxes.map((b,i)=><div key={i} className="absolute border-2 border-amber-400 pointer-events-none" style={{left:b.x*100+'%',top:b.y*100+'%',width:b.width*100+'%',height:b.height*100+'%'}}><span className="bg-black/80 text-xs">{i+1}</span></div>)}</div>{start&&<p>First corner selected. Click the opposite corner.</p>}{boxes.map((b,i)=><p key={i}>{i+1}. {b.label} <button onClick={()=>setBoxes(boxes.filter((_,j)=>i!==j))} className="text-rose-300">Remove</button></p>)}</>}{report.video&&<video controls className="max-h-96 w-full" src={report.video}/>}
 <form className="space-y-3" onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));void run(async()=>{await req(`/readiness/reports/${report.id}/review`,{method:'POST',body:JSON.stringify({...d,annotations:boxes,expected_updated_at:report.updated_at||null})});await select(report.id)})}}><label>Status<select name="status" className={input}><option>VERIFIED</option><option>REJECTED</option><option>DISPATCHED</option><option>RESOLVED</option></select></label><label>Assigned team<input name="assigned_to" className={input} defaultValue={report.assigned_to||''}/></label><label>Reason and verification evidence<textarea name="reason" className={input} required minLength={5}/></label><button disabled={busy} className={button}>Save reviewed decision</button></form><h3 className="font-semibold">Audit history</h3>{history.map(h=><div key={h.id} className="border-t border-slate-700 p-2"><p><When value={h.time}/> · {h.actor} · {h.action}</p><p>{h.after?.reason||h.notice}</p><p>{h.before?.status} → {h.after?.status}</p></div>)}</>}
 </section>
}
function MessagingPanel({run,busy,notify}:Props&{notify:(s:string)=>void}){
 const [recipients,setRecipients]=useState<any[]>([]),[deliveries,setDeliveries]=useState<any[]>([]),[status,setStatus]=useState<any>(null);
 const load=async()=>{const [r,d,s]=await Promise.all([req('/messaging/recipients'),req('/messaging/deliveries'),req('/messaging/status')]);setRecipients(r);setDeliveries(d);setStatus(s)};
 return <section className={panel}><h2 className="text-xl font-semibold">WhatsApp and SMS</h2><p>Register recipients in Settings first. Enable SMS only after recording SMS consent. Each channel has independent delivery status; neither guarantees arrival at the same time.</p><button disabled={busy} className={button} onClick={()=>run(load)}>Load channels and deliveries</button>{status&&<p>SMS: {status.sms.enabled?'enabled':'disabled'} · {status.sms.configured?'configured':status.sms.missing.join(', ')}. WhatsApp test template: {status.whatsapp_test_configured?'configured':'not configured'}.</p>}
 {recipients.map(r=><form key={r.id} className="border-t border-slate-700 py-3 space-y-2" onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));void run(async()=>{await req('/messaging/recipients/'+r.id,{method:'PUT',body:JSON.stringify({whatsapp:d.whatsapp==='on',sms:d.sms==='on',sms_consent_reference:d.sms_consent_reference})});await load();notify('Channel preferences saved')})}}><p>{r.name} · {r.phone}</p><div className="flex gap-5"><label><input type="checkbox" name="whatsapp" defaultChecked={r.whatsapp}/> WhatsApp</label><label><input type="checkbox" name="sms" defaultChecked={r.sms}/> SMS</label></div><label className="block">SMS consent record<input name="sms_consent_reference" className={input} defaultValue={r.sms_consent_reference}/></label><button className={button} disabled={busy}>Save preferences</button><button type="button" disabled={busy} className="ml-3 rounded bg-amber-700 px-3 py-2" onClick={()=>{const channels=[...(r.whatsapp?['whatsapp']:[]),...(r.sms?['sms']:[])];if(!channels.length)return; if(confirm(`Send a labelled TEST to ${r.name} via ${channels.join(' and ')}? Uses saved preferences and may incur provider charges.`))void run(async()=>{await req('/messaging/test',{method:'POST',body:JSON.stringify({recipient_id:r.id,request_id:crypto.randomUUID(),channels,confirmed_test:true})});await load();notify('Test queued. Refresh to check provider delivery status.')})}}>Send test to saved channels</button></form>)}
 <h3 className="font-semibold">SMS and test delivery history</h3><p className="text-sm text-slate-400">Operational WhatsApp delivery history remains in Settings. Refresh to obtain updated states. UNKNOWN requires checking Twilio before resending.</p>{deliveries.map(d=><div key={d.id} className="border-t border-slate-700 py-2 break-words"><strong>{d.channel.toUpperCase()} · {d.test?'TEST':'ALERT'} · {d.status}</strong><p>{d.event_id} · Attempts {d.attempts}</p>{d.twilio_sid&&<p>{d.twilio_sid}</p>}{d.error&&<p className="text-amber-200">{d.error}</p>}</div>)}</section>
}
function ModelPanel({run,busy}:Props){
 const [data,setData]=useState<any>(null),[history,setHistory]=useState<any[]>([]);
 const load=async()=>{setData(await req('/readiness/models'));setHistory(await req('/readiness/audit/model-registry'))};
 return <section className={panel}><h2 className="text-xl font-semibold">Model version controls</h2><p>Candidate artifacts must be installed by a trusted server operator. There is no model-binary upload endpoint. Activation requires an evaluation containing the candidate hash and an explicit review reason.</p><button className={button} disabled={busy} onClick={()=>run(load)}>Load versions</button>{data&&<><p className="break-all">Active SHA-256: {data.active}</p><p>{data.notice}</p><form className="space-y-3" onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(!confirm('Activate this server-installed model? This changes future assessments.'))return;void run(async()=>{await req('/readiness/models/activate',{method:'POST',body:JSON.stringify({...d,evaluation_id:d.evaluation_id||null,rollback:d.rollback==='on',expected_active:data.active})});await load()})}}><label>Candidate<select className={input} name="model_id">{data.versions.map((v:any)=><option key={v.id} value={v.id}>{v.name} · {v.id.slice(0,12)}</option>)}</select></label><label>Evaluation ID<input name="evaluation_id" className={input}/></label><label>Review reason<textarea name="reason" className={input} required minLength={10}/></label><label className="flex gap-2"><input type="checkbox" name="rollback"/>Rollback to a previously active version</label><button className={button} disabled={busy}>Activate reviewed version</button></form><h3>Activation history</h3>{history.map(h=><p key={h.id} className="break-all"><When value={h.time}/> · {h.actor} · {h.to_model?.slice(0,12)} · {h.reason}</p>)}</>}</section>
}
