import React,{useEffect,useState} from 'react';
import {accessApi as api,Identity} from '../services/access';
const card='rounded-xl border border-slate-700 bg-slate-900 p-5';
const activeStates=['AWAITING','ACCEPTED','EN_ROUTE','ARRIVED'];
export function ResponderOverview({who,onOpen}:{who:Identity;onOpen:(id?:string)=>void}){
 const [incidents,setIncidents]=useState<any[]>([]),[team,setTeam]=useState<any>(null),[shelters,setShelters]=useState<any[]>([]),[roads,setRoads]=useState<any[]>([]),[error,setError]=useState(''),[updated,setUpdated]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[newAlerts,setNewAlerts]=useState(0);
 const seen=React.useRef<Set<string>|null>(null);
 useEffect(()=>{let live=true;async function refresh(){try{const [ii,t,s,r]=await Promise.all([api('/dispatch/incidents'),api('/dispatch/my-team'),api('/dispatch/shelters'),who.role==='police'?api('/operations/roads'):Promise.resolve([])]);if(!live)return;const ids=new Set<string>(ii.map((i:any)=>i.id));if(seen.current){const added=[...ids].filter(id=>!seen.current!.has(id)).length;if(added)setNewAlerts(v=>v+added)}seen.current=ids;setIncidents(ii);setTeam(t);setShelters(s);setRoads(r);setUpdated(new Date().toLocaleTimeString());setError('')}catch(e:any){if(live)setError(e.message)}}void refresh();const timer=setInterval(refresh,15000);return()=>{live=false;clearInterval(timer)}},[who.role]);
 const mine=(i:any)=>i.assignments.filter((a:any)=>a.team_id===who.team_id);
 const active=incidents.filter(i=>i.status==='ACTIVE'&&mine(i).some((a:any)=>activeStates.includes(a.status)));
 const pending=active.filter(i=>mine(i).some((a:any)=>a.status==='AWAITING'));
 const overdue=pending.filter(i=>mine(i).some((a:any)=>a.status==='AWAITING'&&Date.parse(a.due_at)<Date.now()));
 const closed=incidents.filter(i=>mine(i).some((a:any)=>a.status==='COMPLETED')).length;
 const visible=incidents.filter(i=>(filter==='all'||filter==='pending'&&pending.includes(i)||filter==='active'&&active.includes(i))&&`${i.title} ${i.location_id} ${i.severity}`.toLowerCase().includes(query.toLowerCase()));
 const stale=team?.updated_at?Date.now()-Date.parse(team.updated_at)>12*3600000:true;
 const medical=who.role==='medical',police=who.role==='police';
 return <section className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-teal-300">RESPONSE WORKSPACE</p><h2 className="text-xl font-bold">{team?.name||'Your team'} · {medical?'Medical readiness':police?'Site security & access':'Rescue & evacuation readiness'}</h2></div><p className="text-sm text-slate-400">Refreshes every 15s · {updated?'Updated '+updated:'Connecting…'}</p></div>{error&&<p role="alert" className="rounded-lg border border-amber-700 p-3 text-amber-200">Unable to refresh: {error}. Displayed data may be stale.</p>}{newAlerts>0&&<div role="status" className="rounded-lg border border-teal-400 bg-teal-950 p-4 flex justify-between gap-3"><strong>{newAlerts} new incident alert{newAlerts>1?'s':''}. Review and acknowledge below.</strong><button onClick={()=>setNewAlerts(0)} className="underline">Dismiss</button></div>}<div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Awaiting acknowledgement',pending.length],['Active responses',active.length],['Overdue acknowledgements',overdue.length],['Completed assignments',closed]].map(([label,n])=><div className={card} key={label}><p className="text-sm text-slate-400">{label}</p><strong className="block text-3xl mt-2">{n}</strong></div>)}</div>
 {team&&<div className={card+' space-y-3'}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">Team capacity · {team.availability}</h3><button className="text-teal-300 underline" onClick={()=>onOpen()}>Update availability / resources</button></div><div className="flex flex-wrap gap-6"><span>Personnel: <strong>{team.personnel}</strong></span>{medical&&<><span>Reported beds: <strong>{team.beds}</strong></span><span>Ambulances: <strong>{team.ambulances}</strong></span></>}<span>Coverage: {team.coverage.join(', ')}</span></div><p className="text-sm text-slate-400">{team.equipment||'No equipment recorded'} · Last reported {new Date(team.updated_at).toLocaleString()}{stale?' · STALE — update capacity':''}. These counts are manually reported.</p></div>}
 {police&&<div className={card}><h3 className="font-semibold">Recorded road network</h3><p className="mt-2">{roads.filter(r=>r.effective_status==='blocked').length} blocked · {roads.filter(r=>r.effective_status==='restricted').length} restricted · {roads.filter(r=>r.stale||r.effective_status==='unknown').length} stale / unknown</p><p className="text-sm text-slate-400">Use Road conditions to update surveyed roads. Counts cover the recorded network, not only assigned incidents.</p></div>}
 {!medical&&!police&&<div className={card}><h3 className="font-semibold">Shelter readiness</h3><p className="mt-2">{shelters.filter(s=>s.status==='OPEN'&&!s.stale).length} open shelters with recent reports · {shelters.filter(s=>s.status==='OPEN'&&!s.stale).reduce((n,s)=>n+(s.available_spaces||0),0)} reported spaces</p><p className="text-sm text-slate-400">Directory totals are not reservations or proof of safe access. Confirm locally before evacuating.</p></div>}
 <div className="flex flex-wrap gap-3"><label className="flex-1 min-w-[180px]"><span className="sr-only">Search incidents</span><input className="w-full rounded-lg border border-slate-600 bg-slate-900 p-3" placeholder="Search incident, site or severity…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label><span className="sr-only">Incident filter</span><select className="rounded-lg border border-slate-600 bg-slate-900 p-3" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All assigned incidents</option><option value="pending">Awaiting acknowledgement</option><option value="active">Active responses</option></select></label></div><div className="grid md:grid-cols-2 gap-4">{visible.map(i=><article className={card+' space-y-3'} key={i.id}><div className="flex flex-wrap justify-between gap-2"><strong>{i.title}</strong><span className="text-amber-300">{i.severity}</span></div>{i.drill&&<p className="text-amber-200 font-semibold">EXERCISE — no real emergency</p>}<p>{i.description}</p><p className="text-sm">{i.verification?`Verified by ${i.verification.by} · ${new Date(i.verification.at).toLocaleString()}`:'Coordinator-created incident'}</p><div className="grid grid-cols-2 gap-2 text-sm"><span>Reported affected: {i.affected_people??'Unknown'}</span><span>Reported injured: {i.site_details?.reported_injured??'Unknown'}</span><span>Access: {i.site_details?.access_condition||'unknown'}</span><span>Incident: {i.status}</span></div>{mine(i).map((a:any)=><div key={a.id} className="rounded-lg bg-slate-950 p-3"><strong>{a.status.replace(/_/g,' ')}</strong><p className="text-sm">{a.task}</p><p className="text-sm text-slate-400">Respond by {new Date(a.due_at).toLocaleString()} · ETA {a.eta_minutes==null?'not reported':a.eta_minutes+' min'}</p></div>)}<div className="flex flex-wrap gap-4"><button className="rounded-lg bg-teal-700 px-4 py-2" onClick={()=>onOpen(i.id)}>Open alert / evidence / respond</button><a className="text-teal-300 underline py-2" target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${i.latitude}&mlon=${i.longitude}#map=15/${i.latitude}/${i.longitude}`}>Site map</a></div></article>)}</div>{!visible.length&&<p className={card}>No matching team incidents. New coordinator-approved alerts will appear here automatically.</p>}</section>
}
